---
# tasks file to start adminer container

- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} adminer container"
  docker_container:
    name: adminer
    image: adminer:{{ docker_adminer_image }}
    restart_policy: always
    tty: yes
    links: 
      - 'nextcloud-db:db'
    networks:
      - name: backend
    networks_cli_compatible: true
    labels:
      traefik.docker.network: "frontend"
      traefik.enable:         "true"
      traefik.frontend.rule:  "Host:{{ nextcloud_server_fqdn }}; PathPrefixStrip:/adminer"
      traefik.port:           "8080"
      traefik.protocol:       "http"
      traefik.frontend.headers.referrerPolicy:       "no-referrer"
      traefik.frontend.headers.SSLRedirect:          "true"
      traefik.frontend.headers.STSSeconds:           "315360000"
      traefik.frontend.headers.browserXSSFilter:     "true"
      traefik.frontend.headers.contentTypeNosniff:   "true"
      traefik.frontend.headers.forceSTSHeader:       "true"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload:           "true"
      traefik.frontend.headers.frameDeny:            "true"
      com.centurylinklabs.watchtower.enable:         "true"
    state: "{{ state | default('started') }}"
      