---
# tasks file to start adminer container

- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} adminer container"
  docker_container:
    name: adminer
    image: adminer:{{ docker_adminer_image }}
    restart_policy: always
    tty: yes
    links: 
      - 'nextcloud-db:db'
    networks:
      - name: backend
    networks_cli_compatible: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.adminer-http.entrypoints: "web"
      traefik.http.routers.adminer-http.rule: "Host(`{{ adminer_server_fqdn }}`)"
      traefik.http.routers.adminer-http.middlewares: "adminer-https@docker"
      traefik.http.middlewares.adminer-https.redirectscheme.scheme: "https"
      traefik.http.routers.adminer.entrypoints: "web-secure"
      traefik.http.routers.adminer.rule: "Host(`{{ adminer_server_fqdn }}`)"
      traefik.http.routers.adminer.tls: "true"
      traefik.http.routers.adminer.tls.certresolver: "default"
      com.centurylinklabs.watchtower.enable: "true"
    state: "{{ state | default('started') }}"
      