---
# tasks file for docker_container
# start all needed container

- name: docker network
  include_tasks: network.yml
  when: state is undefined or 'absent' not in state

- name: docker watchtower
  include_tasks: watchtower.yml

- name: docker traefik
  include_tasks: traefik.yml

- name: docker portainer
  include_tasks: portainer.yml
  when: portainer_enabled|bool

- name: docker database
  include_tasks: database.yml

- name: docker redis
  include_tasks: redis.yml

- name: docker adminer
  include_tasks: adminer.yml
  when: 
    - adminer_enabled|bool
    - nextcloud_db_type != 'sqlite'

- name: docker nextcloud
  include_tasks: nextcloud.yml

- name: docker nginx
  include_tasks: nginx.yml
  when: "'fpm' in docker_nextcloud_image"

- name: docker onlyoffice
  include_tasks: onlyoffice.yml
  when: online_office == 'onlyoffice'
  
- name: docker collabora office
  include_tasks: collabora.yml
  when: 
    - online_office == 'collabora'
    - ansible_architecture == 'x86_64'

- name: docker turnserver
  include_tasks: turnserver.yml
  when: 
    - talk_install|bool
    - ansible_architecture == 'x86_64'

- name: docker network
  include_tasks: network.yml
  when: state is defined and 'absent' in state
