---
# CentOS related tasks

- name: add epel repo
  yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux 7 - $basearch
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
    gpgkey: https://getfedora.org/static/352C64E5.txt
    gpgcheck: yes
    failovermethod: priority
    enabled: 1

- name: update os
  yum:
    name: '*'
    update_cache: true
    state: latest
  vars:
      ansible_python_interpreter: python2

- name: install needed packages
  yum:
    name:
      - zip
      - unzip
      - bzip2
      - screen
      - python3-pip
      - curl
      - wget
      - facter
      - policycoreutils-python
      - libselinux-python
    state: latest
    enablerepo: epel 
  vars:
    ansible_python_interpreter: python2

- name: install pip3 packages
  pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  loop:
    - pip
    - selinux

- name: turn on selinux
  selinux:
    policy: targeted
    state: enforcing
  vars:
    ansible_python_interpreter: python2

