---
# Ubuntu related OS tasks

- name: remove ubuntu repo docker
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent
    
- name: install needed packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - python-pip
      - software-properties-common
    state: latest

- name: add docker key
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: 
    - https://download.docker.com/linux/ubuntu/gpg

- name: add additional docker repo
  apt_repository:
    repo: "{{ item }}"
    validate_certs: true
    update_cache: true
    state: present
  with_items:
    - deb [arch={{ pkg_architekture[ansible_architecture] }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: install docker
  apt:
    name: 
      - docker-ce
      - python-docker
      
    state: latest
 